name: Data Pipeline

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * 0' # Run weekly on Sunday at 2 AM

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    steps:
      # Needed for ohsome-planet CLI tool to convert .osm.pbf -> .parquet
      - name: Checkout ohsome-planet repository instead of this repository
        uses: actions/checkout@v3
        with:
          repository: 'GIScience/ohsome-planet'
          submodules: true

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Cache ohsome-planet JAR
        uses: actions/cache@v3
        id: jar-cache
        with:
          path: ohsome-planet-cli/target/ohsome-planet.jar
          key: ${{ runner.os }}-ohsome-planet-${{ hashFiles('**/pom.xml') }}

      - name: Install ohsome-planet
        if: steps.jar-cache.outputs.cache-hit != 'true'
        run: |          
          ./mvnw clean package -DskipTests

      - name: Prepare DuckDB dependency
        run: |
          wget https://github.com/duckdb/duckdb/releases/download/v1.1.0/duckdb_cli-linux-amd64.zip
          unzip duckdb_cli-linux-amd64.zip
          chmod a+x ./duckdb

      - name: Test DuckDB & Ohsome planet
        run: |
          ./duckdb :memory: "SELECT 1"
          java -jar ohsome-planet-cli/target/ohsome-planet.jar --help

      - name: Process Monaco
        run: |
          curl -O https://download.geofabrik.de/europe/monaco-latest.osm.pbf
          java -jar ohsome-planet-cli/target/ohsome-planet.jar contributions --pbf=monaco-latest.osm.pbf --parallel=$(nproc) --output monaco
          ./duckdb -c "
              INSTALL 'spatial';
              LOAD 'spatial';
              COPY (
                  SELECT 
                      osm_type::ENUM ('node', 'way', 'relation') AS osm_type,
                      osm_id,
                      tags,
                      bbox,
                      ST_GeomFromWKB(geometry) as geometry,
                  FROM 'monaco/contributions/latest/*.parquet'
                  ORDER BY bbox.xmin, bbox.ymin, bbox.xmax, bbox.ymax
              ) TO 'monaco.osm.parquet' (
                  FORMAT PARQUET,
                  CODEC 'zstd',
                  COMPRESSION_LEVEL 20
                  FORMAT PARQUET,
                  PARQUET_VERSION v2
              );
          "
      - name: Test Monaco data
        run: |
          ./duckdb -c "
            LOAD 'spatial';
            SUMMARIZE FROM 'monaco.osm.parquet'
          "
      #- name: Upload to R2
      #  env:
      #    CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      #    CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      #  run: |
      #    npm install -g wrangler
      #    wrangler r2 object put "osm-data/monaco.osm.parquet" --file="monaco.osm.parquet"
      #    wrangler r2 object put "osm-data/estonia.osm.parquet" --file="estonia.osm.parquet"
