name: Convert OSM data to Geoparquet & Upload to Hugging face

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * 0' # Run weekly on Sunday at 2 AM

env:
  DUCKDB_VERSION: '1.4.0'
  OHSOME_PLANET_VERSION: '1.1.0'

jobs:
  download-convert-and-upload:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          # Europe
          - continent: europe
            country: albania
          - continent: europe
            country: andorra
          - continent: europe
            country: austria
          - continent: europe
            country: azores
          - continent: europe
            country: belarus
          - continent: europe
            country: belgium
          - continent: europe
            country: bosnia-herzegovina
          - continent: europe
            country: bulgaria
          - continent: europe
            country: croatia
          - continent: europe
            country: cyprus
          - continent: europe
            country: czech-republic
          - continent: europe
            country: denmark
          - continent: europe
            country: estonia
          - continent: europe
            country: faroe-islands
          - continent: europe
            country: finland
          - continent: europe
            country: france
          - continent: europe
            country: georgia
          - continent: europe
            country: germany
          - continent: europe
            country: greece
          - continent: europe
            country: guernsey-jersey
          - continent: europe
            country: hungary
          - continent: europe
            country: iceland
          - continent: europe
            country: ireland-and-northern-ireland
          - continent: europe
            country: isle-of-man
          - continent: europe
            country: italy
          - continent: europe
            country: kosovo
          - continent: europe
            country: latvia
          - continent: europe
            country: liechtenstein
          - continent: europe
            country: lithuania
          - continent: europe
            country: luxembourg
          - continent: europe
            country: macedonia
          - continent: europe
            country: malta
          - continent: europe
            country: moldova
          - continent: europe
            country: monaco
          - continent: europe
            country: montenegro
          - continent: europe
            country: netherlands
          - continent: europe
            country: norway
          - continent: europe
            country: poland
          - continent: europe
            country: portugal
          - continent: europe
            country: romania
          - continent: europe
            country: russia
          - continent: europe
            country: serbia
          - continent: europe
            country: slovakia
          - continent: europe
            country: slovenia
          - continent: europe
            country: spain
          - continent: europe
            country: sweden
          - continent: europe
            country: switzerland
          - continent: europe
            country: turkey
          - continent: europe
            country: ukraine
          - continent: europe
            country: united-kingdom
    steps:
      # Needed for ohsome-planet CLI tool to convert .osm.pbf -> .parquet
      - name: Checkout ohsome-planet repository instead of this repository
        uses: actions/checkout@v3
        with:
          repository: 'GIScience/ohsome-planet'
          submodules: true
          ref: ${{ env.OHSOME_PLANET_VERSION }}

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      
      - name: Cache ohsome-planet JAR
        uses: actions/cache@v3
        id: jar-cache
        with:
          path: ohsome-planet-cli/target/ohsome-planet.jar
          key: ${{ runner.os }}-ohsome-planet-${{ env.OHSOME_PLANET_VERSION }}

      - name: Install ohsome-planet
        if: steps.jar-cache.outputs.cache-hit != 'true'
        run: |          
          ./mvnw clean package -DskipTests

      - name: Install DuckDB
        run: |
          wget https://github.com/duckdb/duckdb/releases/download/v${{ env.DUCKDB_VERSION }}/duckdb_cli-linux-amd64.zip
          unzip duckdb_cli-linux-amd64.zip
          chmod a+x ./duckdb
      
      - name: Install Hugging Face CLI
        run: pip install huggingface_hub[cli]

      - name: Test Dependencies
        run: |
          hf version
          ./duckdb :memory: "SELECT 1"
          java -jar ohsome-planet-cli/target/ohsome-planet.jar --help

      - name: Process ${{ matrix.country }}
        run: |
          mkdir -p data/continent=${{ matrix.continent }}/country=${{ matrix.country }}
          curl -L -O https://download.geofabrik.de/${{ matrix.continent }}/${{ matrix.country }}-latest.osm.pbf
          java -jar ohsome-planet-cli/target/ohsome-planet.jar contributions \
            --pbf=${{ matrix.country }}-latest.osm.pbf --parallel=$(nproc) --output ${{ matrix.country }}
          ./duckdb -c "
              INSTALL 'spatial';
              LOAD 'spatial';
              COPY (
                  SELECT
                      osm_type::ENUM ('node', 'way', 'relation') AS osm_type,
                      osm_id,
                      tags,
                      bbox,
                      ST_GeomFromWKB(geometry) as geometry,
                  FROM '${{ matrix.country }}/contributions/latest/*.parquet'
                  ORDER BY bbox.xmin, bbox.ymin, bbox.xmax, bbox.ymax
              ) TO 'data/continent=${{ matrix.continent }}/country=${{ matrix.country }}/data.parquet' (
                  FORMAT PARQUET,
                  CODEC 'zstd',
                  COMPRESSION_LEVEL 20,
                  PARQUET_VERSION v2
              );
          "
      - name: Test ${{ matrix.country }} data
        run: |
          ./duckdb -c "
            LOAD 'spatial';
            SUMMARIZE FROM 'data/continent=${{ matrix.continent }}/country=${{ matrix.country }}/data.parquet';
          "

      - name: Upload to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: hf upload --repo-type dataset open2roam/openstreetmaps ./data
      
